# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjSlTY7DADhLsYOZn8ZpIyB7xA3pPGzv
"""

calif=[]
califica=0
def promedio(calif,sum):
  sum=0
  c=[]
  for i in range(10):
    print("Dame la calificacion")
    c2 = float(input())
    calif.append(c2)
    if  (c2>=8.5):
      sum=sum+1
  return (sum)
print("estos son los que tienen mayor promedio de 8.5 son: ", promedio(calif, sum))